# Generated by Django 5.0.4 on 2024-04-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='defficulty',
            new_name='difficulty',
        ),
    ]
