# Generated by Django 5.0.4 on 2024-04-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_rename_defficulty_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
